version: '3.8'

services:
  drupal:
    build: .
    ports:
      - '8080:80'
    volumes:
      - drupal_data:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:10.5
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql

volumes:
  drupal_data:
  db_data:
